[package]
name = "supervisor-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.18.1", features = ["v4"] }
